- AMScrollingNavbar/UIViewController+ScrollingNavbar.m
When programmatically affixing the `topLayoutGuide` to the top of the view, the constraint can be defined either with the topLayoutGuide as the `firstItem` or `secondItem` in the relationship. Both are correct, but the constraint's `constant` must be flipped accordingly, as neither order should be assumed by the library.
> Fixed topLayoutGuide constraint reversal causing navBar hiding to be reversed

- .gitignore
- AMScrollingNavbar.xcodeproj/project.pbxproj
- AMScrollingNavbar.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- AMScrollingNavbar.xcodeproj/xcshareddata/xcschemes/AMScrollingNavbar.xcscheme
- AMScrollingNavbar/AMScrollingNavbar.h
- AMScrollingNavbar/Info.plist
[Carthage](https://github.com/Carthage/Carthage) - A simple, decentralized dependency manager for Cocoa by the Github team
* Ignore `Carthage/Build` as a file in `.gitignore`
- Carthage will create that folder as a symlink, so it has to be ignored as a file
* Make project build-able for Carthage
* Add project file
* Share scheme
I am using Carthage in my own project and using it to manage AMScrollingNavbar. 
PS.
Great work. Thank you for all the time this project saved me.
> Add support for Carthage

- AMScrollingNavbar.xcodeproj/project.pbxproj
- Source/ScrollingNavbar.swift
Before this fix, when using Carthage and importing this framework into a target supports iOS version lower than 8.4 will get following error
```
Module file's minimum deployment target is ios8.4 v8.4: .../Carthage/Build/iOS/AMScrollingNavbar.framework/Modules/AMScrollingNavbar.swiftmodule/x86_64.swiftmodule
```
Thank you for updating the project to Swift. :+1:
> Set iOS deployment target to 8.0 (was 8.4 by default)

- Source/ScrollingNavigationController.swift
Should only change the color attribute.
> Prevent overwriting users' navigation bar title attribute.

- Source/ScrollingNavigationController.swift
This commit: https://github.com/andreamazz/AMScrollingNavbar/commit/ceffb9dca7acdccc1058c0e669dc747dec080e61 wasn't fixing the issue for me.  Instead of preventing this gesture recognizer from recognizing touches simultaneously with other GRs, I think we should block touch events entirely when `scrollingEnabled` is `false`.
> Fix `scrollEnabled` implementation

- Source/ScrollingNavigationController.swift
In my case i have horizontal UICollectionView, which cells need to requireGestureRecognizerToFail of navigationController gesture, so i needed to expose gestureRecognizer property and handle Failure state. This Fix #193 which i opened.
> Expose gestureRecognizer property and handle failover of gesture

- Source/ScrollingNavigationController.swift
* the controller is visible but not on top causes the view frame being at the wrong y- location.
> fixes an issue when search controller is visible

- Source/ScrollingNavigationController.swift
I created a variable where to store the source TabBar frame and translucent, then I assign it on followScrollView method and I use it to get back to original translucent state when tabbar is on its original frame.
Everything is not force unwrapped.
Tested on iOS 10
Hope You like it!
> Implementation of tabbar as Follower

- Source/ScrollingNavigationController.swift
When there is a horizontally scrollable view inside the followed scrollview, the navigation bar moves slightly up and down as described by #230. This is because ScrollingNavigationController pan gesture recognizer allows simultaneous gestures. This pull requests adds a guard preventing the pan gesture to start unless it is vertical
> Prevent conflicts with horizontally scrollable views

- Demo/ScrollingNavbarDemo/ViewControllers/TableViewController.swift
- Source/ScrollingNavbar+Sizes.swift
This PR addresses https://github.com/andreamazz/AMScrollingNavbar/issues/271. The navigation bar will now show up immediately when the user is scrolling from the bottom of the scroll view with a significant `contentInset` set. I've also updated the demo app to demonstrate a table view with extra bottom inset to trigger the correct behaviour.
> Include contentInset when calculating scroll view's contentSize

- Source/ScrollingNavbar+Sizes.swift
This is for https://github.com/andreamazz/AMScrollingNavbar/issues/273
I've noticed inconsistencies between bounds of the screen and presented view controller when an extended status bar is visible and I made a simple adjustment . I've checked this in iPhone X simulator and it looks like it is not an issue on that device. Below a quick screen grab of the fix:
> Fix for extended status bar issue

- Source/ScrollingNavigationController.swift
Fixed issue with button items not fading on iOS 11 #257
> Fixed issue with button items not fading on iOS 11

- Source/ScrollingNavigationController.swift
Fixes bug when `updateNavbarAlpha()` method was not working correctly when there is a modally presented view controller.
> Fixes #275 when navbar subviews are hidden

- Source/ScrollingNavbar+Sizes.swift
We have a "No internet" view that shows up in the bottom of our app which is added to the application window. When it is showing, the navigation bar does not expand fully due to the computation of extendedStatusBarDifference.
This fixes the issue
> Added support for custom UIScreen height

- Source/ScrollingNavigationController.swift
Hi. It seems that at some point the `hideNavbar` method has ceased to be supported and now it does not work
> Fix hideNavbar method

- Source/ScrollingNavigationController.swift
> Add support for child view controller's layout preferences.

- AMScrollingNavbar.podspec
- Source/ScrollingNavbar+Sizes.swift
Apple have started to clamp down on the use of deprecated APIs. In AMScrollingNavBar/ScrollingNavbar+Sizes.swift there is reference to this deprecated control.
This fork and pull request fixes the issue.
(ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs)
> Remove the deprecated API usage problem

- Source/ScrollingNavigationController.swift
Context: under most circumstances, UIKit will automatically dim the navigation bar when the keyboard pops up (unless [tintAdjustmentMode](https://developer.apple.com/documentation/uikit/uiview/1622555-tintadjustmentmode) is set to `normal`)
If `ScrollingNavigationController`'s `updateNavbarAlpha()` is called while the keyboard is up, the line `navigationBar.tintColor = navigationBar.tintColor.withAlphaComponent(alpha)` will cause the dimmed tint to be permanent.
The events `windowDidBecomeVisible` and `didRotate` will typically be fired when the keyboard pops up. For both events `showNavbar()` will be invoked, which in turn will call `updateNavbarAlpha()` and exit immediately. This call to `updateNavbarAlpha()` can be harmful as described above, and I can't see a scenario where it would …
> Bug fix: updateNavbarAlpha() unnecessarily persisting dimmed tint

- Source/ScrollingNavigationController.swift
I had an issue where i was showing a full screen image and when closed the navbar would automatically expand because of the notification DidBecomeVisible.
I see that you have a boolean value DidBecomActive and i thought it might be useful for someone else to have control and disable DidBecomeActive not to show the navbar from default.
hope this gets merged :)
Thanks for your awesome library
> added expandOnVisible

- Source/ScrollingNavigationController.swift
@andreamazz 
In my configuration i have a follower and underneath it i have another Uiview as a sticky view.
Under the sticky view i have my tableview
I realised that the scrollToTop does not go the correct position because i needed to add some offset in some views.
with this additionalScrollToTopOffset gets to the exact correct position.
Hope this gets merged to master :) 
maybe will be usefull to others as well
> Adding  additionalScrollToTopOffset variable

- Source/ScrollingNavbar+Sizes.swift
- Source/ScrollingNavigationController.swift
I added followersHeight in ScrollingNavbar+Sizes to use it anywhere needed.
Fixed the issue that it would not scroll.
The case was when the UINavigationBar.appearance().isTranslucent = false was not working correctly when the navbar was collapsed.
this fixes issue https://github.com/andreamazz/AMScrollingNavbar/issues/379
> Change shouldScrollWithDelta to take in account the followersHeight

- Source/ScrollingNavigationController.swift
The previous fix was wrong.
This is the correct value for the case when there is no searchController in the navigationBar.
This fix  doesnt handle the case for .isTranslucent = false with searchController in the navigationBar.
I couldnt handle it because the checkSearchController(delta) was not really working correct to take that in account as well.
I also think updateContentInset are also wrong when the searchController exists for .isTranslucent = false
> issue 379 fix

- Source/ScrollingNavigationController.swift
This fixes a bug where the Nav Bar expands after being collapsed, but looks empty under some circumstances.
This happens when the the scroll view's `UIViewController` presents a new `UINavigationController` modally (`.overFullScreen`), and after the Nav Bar was previously collapsed by scrolling up. At this point, `windowDidBecomeVisible()` is called, which in turns calls `showNavbar()`.
When `showNavbar()` executes at this point, the value of the state is `.expanded` so the method call simply exits without doing anything.  The issue is that the alpha value was set to zero when the Nav Bar was previously collapsed, and it is still zero at this stage so the Nav Bar appears empty.
This fixes the immediate issue at hand, and I am pretty confident that the change doesn't cause any harm.
This …
> showNavbar() should set opacity to 1 when state is expanded

- README.md
- Source/ScrollingNavigationController.swift
Updated so `ScrollingNavigationController` now maintains its own copy of the UINavigationBar's `tintColor` property - thus avoiding situations where UIKit-applied dimming is accidentally made permanent through a combination of UIAlert + device rotation for example.
More context at #391
> UIKit-applied dimming bug fixed by duplicating tintColor value

- Source/ScrollingNavigationController.swift
Hi, @andreamazz 
Thank you for the cool library.
After hiding the navigation bar, the back button text color changed from transparent to black.
And I solved the problem.
|Before|After|
|:--:|:--:|
|![before](https://user-images.githubusercontent.com/25205138/87564617-92c9a180-c6fb-11ea-985c-3e6269eddef3.gif)|![after](https://user-images.githubusercontent.com/25205138/87564646-9d843680-c6fb-11ea-894e-bd148982a332.gif)|
Updating the navigation appearance in sample app is the following.
```
extension UINavigationController {
func setupCustomNavigation() {
let clear = [NSAttributedString.Key.foregroundColor: UIColor.clear]
if #available(iOS 13.0, *) {
let barAppearance = UINavigationBarAppearance()
// Hide back button title.
let barButtonAppearance = UIBarButtonItemAppearance() …
```
> The back button text color changed from transparent to black.

- Source/ScrollingNavigationController.swift
Fixed #398  by using IOS 13+ APIs to update titleTextAttributes across all possible NavigationBar appearance modes, rather than only in the defaultAppearance.
Could possible use refactoring in future revisions for conciseness. But for now, this fix quickly and properly addresses the issue for developers targetting 13+ and up, that use largeTitles or other new toolbar appearances introduced.
> Hotfix for IOS 13 NavigationBar appearance issues

- Source/ScrollingNavigationController.swift
View controllers pushed on after a previous view controller `stopFollowingScrollView` were not able to use gestural pop unless gesture delegate methods were explictly overridden in the subclasses. This commit restores default system behavior in these delegate methods unless we're handling the gesture recognizer we've installed on the scrollable view.
See documentation on gesture recognizer to confirm default behavior https://developer.apple.com/documentation/appkit/nsgesturerecognizerdelegate
> Ensured that gesture delegate methods do not block gestural pop
